# Generated by Django 5.2.7 on 2025-10-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/'),
        ),
    ]
