# Generated by Django 5.2.7 on 2025-11-03 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Venda'), ('purchase', 'Compra'), ('adjustment', 'Ajuste Manual'), ('return', 'Devolução'), ('damage', 'Avaria'), ('transfer', 'Transferência')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positivo para entrada, negativo para saída')),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='Pedido ID, nota fiscal, etc', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='catalog_sto_variant_3a67e4_idx'), models.Index(fields=['movement_type', '-created_at'], name='catalog_sto_movemen_7bcb98_idx')],
            },
        ),
    ]
