[phases.setup]
nixPkgs = ["python311", "postgresql"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = ["cd backend && pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python manage.py migrate --noinput && gunicorn core.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
