# Generated by Django 6.0.3 on 2026-03-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_color_cartitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_1_sent',
            field=models.BooleanField(default=False, help_text='Email de lembrete 1h enviado'),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_1_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do envio do email 1', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_2_sent',
            field=models.BooleanField(default=False, help_text='Email com cupom 5% enviado'),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_2_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do envio do email 2', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_3_sent',
            field=models.BooleanField(default=False, help_text='Email com cupom 10% enviado'),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_3_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do envio do email 3', null=True),
        ),
    ]
