# Generated by Django 5.2.7 on 2025-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_quantity', models.IntegerField(blank=True, help_text='Deixe vazio para ilimitado', null=True)),
                ('current_sold', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sales/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='flash_sales', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Oferta Relâmpago',
                'verbose_name_plural': 'Ofertas Relâmpago',
                'ordering': ['-start_time'],
            },
        ),
    ]
