# Generated by Django 5.2.7 on 2025-11-03 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCartMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_abandoned', models.IntegerField(default=0)),
                ('total_value_abandoned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emails_sent_1h', models.IntegerField(default=0)),
                ('emails_sent_24h', models.IntegerField(default=0)),
                ('emails_sent_72h', models.IntegerField(default=0)),
                ('total_recovered', models.IntegerField(default=0)),
                ('total_value_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Carrinho Abandonado',
                'verbose_name_plural': 'Métricas de Carrinhos Abandonados',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('recovered', 'Recuperado'), ('expired', 'Expirado')], default='active', max_length=20)),
                ('first_email_sent', models.DateTimeField(blank=True, null=True)),
                ('second_email_sent', models.DateTimeField(blank=True, null=True)),
                ('third_email_sent', models.DateTimeField(blank=True, null=True)),
                ('recovery_coupon_1h', models.CharField(blank=True, max_length=50)),
                ('recovery_coupon_24h', models.CharField(blank=True, max_length=50)),
                ('recovery_coupon_72h', models.CharField(blank=True, max_length=50)),
                ('recovery_link_clicks', models.IntegerField(default=0)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_order_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='abandoned_c_user_id_5b6319_idx'), models.Index(fields=['status', 'created_at'], name='abandoned_c_status_3d4e13_idx')],
            },
        ),
    ]
