# Generated by Django 5.2.7 on 2025-11-03 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wishlists', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_30_days_additions', models.IntegerField(default=0)),
                ('trending_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_analytics', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Wishlist Analytics',
                'verbose_name_plural': 'Wishlist Analytics',
                'ordering': ['-total_wishlists'],
            },
        ),
        migrations.CreateModel(
            name='WishlistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_sale', models.BooleanField(default=True)),
                ('notify_on_stock', models.BooleanField(default=True)),
                ('notify_on_price_drop', models.BooleanField(default=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_when_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_when_added', models.IntegerField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlistcollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Queda de Preço'), ('back_in_stock', 'Voltou ao Estoque'), ('on_sale', 'Em Promoção'), ('low_stock', 'Estoque Baixo')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wishlist.wishlistitem')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wishlistcollection',
            index=models.Index(fields=['user', '-created_at'], name='wishlist_wi_user_id_15bb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistcollection',
            index=models.Index(fields=['share_token'], name='wishlist_wi_share_t_ae9976_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistcollection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['collection', '-created_at'], name='wishlist_wi_collect_0e973b_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['product'], name='wishlist_wi_product_2322a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('collection', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlistnotification',
            index=models.Index(fields=['wishlist_item', '-sent_at'], name='wishlist_wi_wishlis_308dd1_idx'),
        ),
    ]
