# Generated by Django 5.2.7 on 2025-11-03 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stockmovement'),
        ('users', '0003_user_email_verified_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_wishlist_items', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
