# Generated by Django 5.2.7 on 2025-11-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_wishlistitem_product_alter_wishlistitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em Processamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em Processamento'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('download_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms', 'Termos de Uso'), ('privacy', 'Política de Privacidade'), ('marketing', 'Comunicações de Marketing'), ('cookies_functional', 'Cookies Funcionais'), ('cookies_analytics', 'Cookies de Análise')], max_length=50)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consent_date'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='users_userc_user_id_c1024d_idx'), models.Index(fields=['consent_date'], name='users_userc_consent_dcce93_idx')],
            },
        ),
    ]
